### ISSUE TITLE
Initial "configuration form" is not displayed

### ISSUE THREAD

**Issue by alexey0511** [digitalocean/droplet-1-clicks#123]
I'm not sure if this is an appropriate place for this issue. ( Please delete it if not )

After creating a new droplet on digital ocean from dokku image. The initial configuiration page is not displayed.

Expected Result:
see initial configuration page 
( as per instructions https://dokku.com/docs/getting-started/install/digitalocean/ ( step 9 )

Actual Result:
displays default Welcome to NGINX page

**Comment by alexey0511** [comment]
What I found so far is that the problem is with NGINX which can't start and gives the error below about mapping port 80
```
[emerg] bind() to [::]:80 failed (98: Unknown error)
```

**Comment by alexey0511** [comment]
Sorted after reading comments and going through the docs...

Removing default nginx site works.

I believe docs could be updated to reflex it.

```
rm /etc/nginx/sites-enabled/default
```

**Comment by GlennOu66304** [comment]
After many times installing new droplets, I found This answer, crossed few buddies on Dokku repo issue raised this one too, but some of them just give up and move to other solutions, please update in the one click installation documentation too.
