### ISSUE TITLE
Discourse: Please wait while we get your droplet ready

### ISSUE THREAD

**Issue by bobbyiliev** [digitalocean/droplet-1-clicks#134]
A community user just reported [here](https://www.digitalocean.com/community/questions/please-wait-while-we-get-your-droplet-ready-i-can-t-connect-via-ssh) that when creating a new [Discourse server from the Marketplace](https://marketplace.digitalocean.com/apps/discourse) they are unable to SSH to the server and they keep getting the following error despite waiting for quite long:

```
Please wait while we get your droplet ready...
```

I was able to replicate the issue a few times with different Droplet sizes.

**Comment by alexeigutium** [comment]
Hello
Thank you for your message. Could you retry? Looks like we fixed the issue, but we're waiting for your check.

Have a good day!

**Comment by bobbyiliev** [comment]
Thank you for the quick fix! Just tested it now and it seems to be all working as expected now.

**Comment by Splicho** [comment]
This still seems to happen for me. Recreated my droplet for the 4th time now, still stuck.

**Comment by bobbyiliev** [comment]
Closing this one as it has been fixed already.

**Comment by jamiecropley** [comment]
I just come across this issue myself today.

**Comment by bobbyiliev** [comment]
> I just come across this issue myself today.

Seems like it might be a similarly new problem. Best to open a new issue instead of continuing the discussion here as the maintainers will miss your comment under this closed issue.

**Comment by jamiecropley** [comment]
> > I just come across this issue myself today.
> 
> Seems like it might be a similarly new problem. Best to open a new issue instead of continuing the discussion here as the maintainers will miss your comment under this closed issue.

I gave it 20 mins and it worked actually, apologies.

**Comment by bobbyiliev** [comment]
> > > I just come across this issue myself today.
> > 
> > 
> > Seems like it might be a similarly new problem. Best to open a new issue instead of continuing the discussion here as the maintainers will miss your comment under this closed issue.
> 
> I gave it 20 mins and it worked actually, apologies.

Ah nice, happy to hear that.

**Comment by jamiecropley** [comment]
Thought I would update that incase anyone else ends up here in future haha
