### ISSUE TITLE
Template.json files Typos

### ISSUE THREAD

**Issue by mberbero** [digitalocean/droplet-1-clicks#26]
Example : https://github.com/digitalocean/droplet-1-clicks/blob/master/rails-20-04/template.json
`  "appiication_name": "Ruby on Rails",`
 ` "appiication_version": "6.0.3.4",`
There some lines start as `appiication`. 
If there is no error in these lines, the issue can be closed.

**Comment by mberbero** [comment]
Fix PR opened 
https://github.com/digitalocean/droplet-1-clicks/pull/27

**Comment by countingtoten** [comment]
Merged
