### ISSUE TITLE
Add iptables restrictions to the default Docker marketplace setup

### ISSUE THREAD

**Issue by nickhammond** [digitalocean/droplet-1-clicks#52]
Can this `Note:` in the ["Getting started after deploying Docker"](https://marketplace.digitalocean.com/apps/docker) be the default setup?

```
Note: The default firewall for the Docker One-Click is UFW, which is a front end to iptables. However, 
Docker modifies iptables directly to set up communication to and from containers. This means that 
UFW won’t give you a full picture of the firewall settings. You can override this behavior in Docker by 
adding --iptables=false to the Docker daemon.
```

The assumption with DO is that things are set up for the best scenario for a developer out of the box, this seems like an easy win to go with better default security to start with.

As mentioned in the second paragraph on the Docker [iptables docmentation](https://docs.docker.com/network/iptables/) "If you’re running Docker on a host that is exposed to the Internet...", you need to restrict IP tables. Newly created droplets on DO are always public, they always get an IPV4 address.

**Comment by CanRau** [comment]
Hmm from [this part](https://docs.docker.com/network/iptables/#prevent-docker-from-manipulating-iptables) it seems it's not that "simple" so might be better to keep iptables as is and let users decide what they want?
