### ISSUE TITLE
Plans for updates to WordPress?

### ISSUE THREAD

**Issue by joshtch** [digitalocean/droplet-1-clicks#87]
Hi, is there any roadmap for updated droplet 1-clicks for existing templates? I am specifically wondering about WordPress.

**Comment by craigusus** [comment]
Same here. Ubuntu 22.10 on WordPress 6.1.1, please!

**Comment by joshtch** [comment]
Agreed, except please (continue to) stick to the Ubuntu LTS version, which is now 22.04.

**Comment by joshtch** [comment]
Looks like this has been resolved by this PR: #95 , which has been merged into master. Thanks!
